# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20170531_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
